In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [12]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
pd.Series([0, 1, 2, 3, 4, 5]) +5

0     5
1     6
2     7
3     8
4     9
5    10
dtype: int64

In [19]:
df = pd.DataFrame({
    'A': [1, 2, 3], 
    'B': [4, 5, 6],
})
print(df)

   A  B
0  1  4
1  2  5
2  3  6


In [24]:
x = np.ones((3,3))
df = pd.DataFrame(x, columns=['A', 'B', 'C'])
print(df)

a = df.to_numpy()
print(a)

     A    B    C
0  1.0  1.0  1.0
1  1.0  1.0  1.0
2  1.0  1.0  1.0
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
import holoviews as hv

In [26]:
np.linrange(0,15,1)

AttributeError: module 'numpy' has no attribute 'linrange'